# App
ENVIRONMENT: "development"
SAMPLE: "merchant.local"
APP_NAME: "service"
APP_PORT: 8001


# Logger
LOG_LEVEL: "info"
LOG_FORMAT: "text"
LOG_SOURCE_LOCATION_ENABLE: false

# Database
DB_HOST: "localhost"
DB_PORT: 5432
DB_NAME: "crewX"
DB_USER: "postgres"
DB_PASSWORD: "postgres"
DB_MAX_POOL_SIZE: 5

# JWT
JWT_SECRET: "some secret"
JWT_EXPIRY_DURATION_HOURS: 1



REDIS_ADDR: "localhost:6379"
REDIS_PASSWORD: ""
REDIS_DB: 0


AWS_REGION: ""
AWS_ACCESS_KEY_ID: ""
AWS_SECRET_ACCESS_KEY: ""
NOTIFICATIONS_EMAIL_ID: ""
NOTIFICATION_FAILURE_TOPIC: ""

VERIFICATION_LINK_BASE_URL: "http://localhost:8080/#/users/verify?verification_token=%s"
DASHBOARD_URL : "http://localhost:8080/"
CONTACT_US_EMAIL : "operations@durianpay.id"

FORGOT_PASSWORD_LINK_BASE_URL: "http://localhost:8080/#/users/reset-password?reset_password_token=%s"
FLIP_KAFKA_TOPIC: "fliptopic"
DISBURSEMENT_BUCKET: "staging-disbursements"
ENCRYPTION_SECRET: "ZHVyaWFuMjAyMA=="
REFUND_SERVICE_GRPC_ADDR: ":9012"
MERCHANT_LOGOS_BUCKET: "test"
POST_PAYMENT_PROCESS_KAFKA_TOPIC: "post_payment_topic"
JWT_DEVICE_TOKEN_EXPIRY_DURATION_HOURS: 24
OTP_EXPIRY_DURATION_MINS: 1
KAFKA_CLIENT_ID_WA: ""
OPS_API_KEY_SECRET: "12345"
PAYMENT_LINK_PREFIX: ""
MERCHANT_AWS_BUCKET: ""
BASIC_SERVICE_PUBLIC_SECRET_KEY: ""
BASIC_SERVICE_PRIVATE_SECRET_KEY: ""
MERCHANT_VERIFICATION_EMAIL_RECEPIENTS: "joobi@durian.money,joobi@keyvalue.systems"
USER_KTP_BUCKET: ""
MERCHANT_FULL_SERVICE_ACTIVATION_EMAIL_RECIPIENTS: ""

VERIJELAS_TOKEN: ""
VERIJELAS_BASE_URL: ""
VERIJELAS_CONSUMER_NAME: ""
VERIJElAS_OCR_PACKAGE_NAME: ""
VERIJElAS_BASIC_ID_PACKAGE_NAME: ""
EKYC_FLIP_ENQUIRY_MERCHANT_ID: ""
DISBURSEMENT_KAFKA_TOPIC: "test"
EMAIL_TEMPLATE_BUCKET: ""
DEFAULT_SUCCESS_REDIRECT_URL: ""
KAFKA_CLIENT_ID_GENERIC_EVENT: ""
METRICS_PORT: 5092
GENERIC_EVENTS_KAFKA_TOPIC: ""
MERCHANT_DEACTIVATE_PAYMENT_COMPLETE_NOTIFICATION: [""]
GRPC_STREAM_CHUNK_SIZE : 1
DAILY_REPORT_BUCKET: ""
BACKUP_REDIS_ADDR: ":6379"
BACKUP_REDIS_DB: 2
BACKUP_REDIS_PASSWORD: ""

SETTLEMENT_BUCKET: "pod2-settlement"
XENDIT_SETTLEMENT_KAFKA_TOPIC: "xendit-settlement"

OY_KAFKA_TOPIC: oy-topic
DANA_EWALLET_REDIRECTION_URL: ""
DANA_REDIRECT_URL: test
OY_BASE_URL: ""

# Replica Database
REPLICA_DB_HOST: postgres_postgres
REPLICA_DB_PORT: 5432
REPLICA_DB_NAME: staging_dpay_server
REPLICA_DB_USER: postgres
REPLICA_DB_PASSWORD: postgres
REPLICA_DB_MAX_POOL_SIZE: 5
AKULAKU_KAFKA_TOPIC: akulaku_callback
AKULAKU_BASE_URL: https://test-pay.akulaku.com
JWT_REFRESH_SECRET: h9MK357g1nM5FoxlwS61
JWT_REFRESH_EXPIRY_DURATION_YEARS: 24
OVO_BASE_URL: https://api.byte-stack.net/pos
DURIANPAY_BANK_TOPUP_KAFKA_TOPIC: durianpay-bank-topup-topic
IS_SANDBOX_DURIANPAY_BANK: false
DURIANPAY_GRPC_CLIENT_ADDRESS: bank_core_banking_service:19100

#dynamic_routing
TSDB_TOKEN: "RzoLqmnnSUV8rfL76HQfYxZ1-_GxiB3h83zliVZK066i8PepaDWvZJyMiEo232rk1p0dWZiwfiso7RoYwXeWlw=="
TSDB_BASE_URL: "http://10.0.6.129:8086/"
TSDB_ROUTING_BUCKET: "staging_routing_stats"
TSDB_ORGANISATION: "Durianpay"
ROUTING_KAFKA_TOPIC: "routing-topic"
ROUTING_MEASUREMENT_NAME: "payment_routing"
ROUTING_DATA_RANGE: "-1h"


VENDOR_API_SECRET_KEY: "V_API_SECRET_KEY"
TEAMS_OPS_ALERT_URL: "https://durianmoney.webhook.office.com/webhookb2/7a3f5b4c-db13-4c34-9197-75679a8cf04a@7f86a0be-de4b-43ee-86af-2ce7f9fd4ce2/IncomingWebhook/310e4d462d744419827acf9ebb05b336/ca6758b9-9efd-4578-bf40-9324b352aa38"
HUBSPOT_BASE_URL: ""
HUBSPOT_API_KEY: ""
LINKAJA_ENCRYPTION_KEY: "uF9sWM1fA0rMk0NBs1RSk0g4J3g8s5Ul"
LINKAJA_BASE_URL: "https://partner-dev.linkaja.com"
LINKAJA_KAFKA_TOPIC: staging_callback_linkaja
SHOPEEPAY_BASE_URL: ""
MITRA_BASE_URL: ""
DANA_REFUND_BASE_URL: ""
MIDTRANS_BASE_URL: ""
PARENT_MERCHANTS: [""]
DB_MAX_IDLE_CONNECTIONS: 2
REPLICA_DB_MAX_IDLE_CONNECTIONS: 2
